export enum Components {
  WAccordion = 'WAccordion',
  WAccordionItem = 'WAccordionItem',
  WAlert = 'WAlert',
  WAlertDescription = 'WAlertDescription',
  WIcon = 'WIcon',
  WAvatar = 'WAvatar',
  WAvatarGroup = 'WAvatarGroup',
  WBadge = 'WBadge',
  WButton = 'WButton',
  WButtonGroup = 'WButtonGroup',
  WInput = 'WInput',
  WCheckbox = 'WCheckbox',
  WKbd = 'WKbd',
  WDivider = 'WDivider',
  WSwitch = 'WSwitch',
}
